{
	normal:
		idle: "idle_all_01"
		walk: "walk_all"
		run: "run_all_01"
		jump: "jump_holding_jump"
		land: "jump_land"
		squat: "cidle_all"
		creep: "cwalk_all"
		prone: "prone_passive"
		crawl: "prone_walkpassive"
	fist:
		idle: "idle_fist"
		walk: "walk_fist"
		run: "run_fist"
		jump: "jump_holding_jump"
		land: "jump_land"
		squat: "cidle_fist"
		creep: "cwalk_fist"
		prone: "prone_knife"
		crawl: "prone_walkpassive"
	something:
		idle: "idle_slam"
		walk: "walk_slam"
		run: "run_slam"
		jump: "jump_holding_jump"
		land: "jump_land"
		squat: "cidle_slam"
		creep: "cwalk_slam"
		prone: "prone_slam"
		crawl: "prone_walkonehand"
	throwing:
		idle: "idle_grenade"
		walk: "walk_grenade"
		run: "run_grenade"
		jump: "jump_holding_jump"
		land: "jump_land"
		squat: "frag_idle_crouch"
		creep: "cwalk_grenade"
		prone: "prone_grenade"
		crawl: "prone_walkonehand"
}